apiVersion: v1
kind: ConfigMap
metadata:
  name: burinake-config
  namespace: burinake-dev
  labels:
    app.kubernetes.io/name: burinake
    app.kubernetes.io/part-of: burinake
    app.kubernetes.io/environment: dev
data:
  SPRING_PROFILES_ACTIVE: "prod"
  POSTGRES_DB: "burinake_dev"
  POSTGRES_HOST: "burinake-pg-368x19.postgres.database.azure.com"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "burinakeadmin"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://burinake-pg-368x19.postgres.database.azure.com:5432/burinake_dev?sslmode=require"
  SPRING_DATASOURCE_USERNAME: "burinakeadmin"
  AI_YOLO_BASE_URL: "http://yolo-server.burinake.svc.cluster.local:8001"
  AI_VLM_BASE_URL: "http://vlm-server.burinake.svc.cluster.local:8002"
  AZURE_BLOB_CONTAINER: "fire-events"
  AZURE_OPENAI_MAX_COMPLETION_TOKENS: "4000"
