apiVersion: v1
kind: ConfigMap
metadata:
  name: burinake-config
  namespace: burinake
  labels:
    app.kubernetes.io/name: burinake
    app.kubernetes.io/part-of: burinake
data:
  SPRING_PROFILES_ACTIVE: "prod"
  POSTGRES_DB: "burinake"
  POSTGRES_HOST: "burinake-pg-368x19.postgres.database.azure.com"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "burinakeadmin"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://burinake-pg-368x19.postgres.database.azure.com:5432/burinake?sslmode=require"
  SPRING_DATASOURCE_USERNAME: "burinakeadmin"
  AI_YOLO_BASE_URL: "http://yolo-server:8001"
  AI_VLM_BASE_URL: "http://vlm-server:8002"
  AZURE_BLOB_CONTAINER: "fire-events"
  AZURE_OPENAI_DEPLOYMENT_NAME: "Burinake-vlm"
  AZURE_OPENAI_API_VERSION: "2024-02-15-preview"
  AZURE_OPENAI_MAX_COMPLETION_TOKENS: "4000"
  VLM_MODEL_PROVIDER: "azure-openai"
