apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: burinake
  namespace: burinake
  labels:
    app.kubernetes.io/name: burinake
    app.kubernetes.io/part-of: burinake
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
